lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "autoslayer"

[packages.directory]
path = "."
editable = true

[[packages]]
name = "easyocr"
version = "1.7.2"

[[packages.wheels]]
name = "easyocr-1.7.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bb/84/4a2cab0e6adde6a85e7ba543862e5fc0250c51f3ac721a078a55cdcff250/easyocr-1.7.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "5be12f9b0e595d443c9c3d10b0542074b50f0ec2d98b141a109cd961fd1c177c"

[[packages]]
name = "filelock"
version = "3.20.3"

[[packages.wheels]]
name = "filelock-3.20.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b5/36/7fb70f04bf00bc646cd5bb45aa9eddb15e19437a28b8fb2b4a5249fac770/filelock-3.20.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "4b0dda527ee31078689fc205ec4f1c1bf7d56cf88b6dc9426c4f230e46c2dce1"

[[packages]]
name = "fsspec"
version = "2026.2.0"

[[packages.wheels]]
name = "fsspec-2026.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e6/ab/fb21f4c939bb440104cc2b396d3be1d9b7a9fd3c6c2a53d98c45b3d7c954/fsspec-2026.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "98de475b5cb3bd66bedd5c4679e87b4fdfe1a3bf4d707b151b3c07e58c9a2437"

[[packages]]
name = "imageio"
version = "2.37.2"

[[packages.wheels]]
name = "imageio-2.37.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/fb/fe/301e0936b79bcab4cacc7548bf2853fc28dced0a578bab1f7ef53c9aa75b/imageio-2.37.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ad9adfb20335d718c03de457358ed69f141021a333c40a53e57273d8a5bd0b9b"

[[packages]]
name = "jinja2"
version = "3.1.6"

[[packages.wheels]]
name = "jinja2-3.1.6-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "85ece4451f492d0c13c5dd7c13a64681a86afae63a5f347908daf103ce6d2f67"

[[packages]]
name = "lazy-loader"
version = "0.4"

[[packages.wheels]]
name = "lazy_loader-0.4-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/83/60/d497a310bde3f01cb805196ac61b7ad6dc5dcf8dce66634dc34364b20b4f/lazy_loader-0.4-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "342aa8e14d543a154047afb4ba8ef17f5563baad3fc610d7b15b213b0f119efc"

[[packages]]
name = "markupsafe"
version = "3.0.3"

[[packages.wheels]]
name = "markupsafe-3.0.3-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/28/52/182836104b33b444e400b14f797212f720cbc9ed6ba34c800639d154e821/markupsafe-3.0.3-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "bdc919ead48f234740ad807933cdf545180bfbe9342c2bb451556db2ed958581"

[[packages]]
name = "mpmath"
version = "1.3.0"

[[packages.wheels]]
name = "mpmath-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a0b2b9fe80bbcd81a6647ff13108738cfb482d481d826cc0e02f5b35e5c88d2c"

[[packages]]
name = "networkx"
version = "3.6.1"

[[packages.wheels]]
name = "networkx-3.6.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/9e/c9/b2622292ea83fbb4ec318f5b9ab867d0a28ab43c5717bb85b0a5f6b3b0a4/networkx-3.6.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d47fbf302e7d9cbbb9e2555a0d267983d2aa476bac30e90dfbe5669bd57f3762"

[[packages]]
name = "ninja"
version = "1.13.0"

[[packages.wheels]]
name = "ninja-1.13.0-py3-none-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/29/45/c0adfbfb0b5895aa18cec400c535b4f7ff3e52536e0403602fc1a23f7de9/ninja-1.13.0-py3-none-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "fb8ee8719f8af47fed145cced4a85f0755dd55d45b2bddaf7431fa89803c5f3e"

[[packages]]
name = "numpy"
version = "2.4.2"

[[packages.wheels]]
name = "numpy-2.4.2-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/05/cb/eff72a91b2efdd1bc98b3b8759f6a1654aa87612fc86e3d87d6fe4f948c4/numpy-2.4.2-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "068cdb2d0d644cdb45670810894f6a0600797a69c05f1ac478e8d31670b8ee75"

[[packages]]
name = "opencv-python-headless"
version = "4.13.0.92"

[[packages.wheels]]
name = "opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/4a/90/b338326131ccb2aaa3c2c85d00f41822c0050139a4bfe723cfd95455bd2d/opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "77a82fe35ddcec0f62c15f2ba8a12ecc2ed4207c17b0902c7a3151ae29f37fb6"

[[packages]]
name = "packaging"
version = "26.0"

[[packages.wheels]]
name = "packaging-26.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b7/b9/c538f279a4e237a006a2c98387d081e9eb060d203d8ed34467cc0f0b9b53/packaging-26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b36f1fef9334a5588b4166f8bcd26a14e521f2b55e6b9de3aaa80d3ff7a37529"

[[packages]]
name = "pillow"
version = "12.1.1"

[[packages.wheels]]
name = "pillow-12.1.1-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/40/72/4c245f7d1044b67affc7f134a09ea619d4895333d35322b775b928180044/pillow-12.1.1-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "50480dcd74fa63b8e78235957d302d98d98d82ccbfac4c7e12108ba9ecbdba15"

[[packages]]
name = "pip"
version = "26.0.1"

[[packages.wheels]]
name = "pip-26.0.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/de/f0/c81e05b613866b76d2d1066490adf1a3dbc4ee9d9c839961c3fc8a6997af/pip-26.0.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bdb1b08f4274833d62c1aa29e20907365a2ceb950410df15fc9521bad440122b"

[[packages]]
name = "pyclipper"
version = "1.4.0"

[[packages.wheels]]
name = "pyclipper-1.4.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/e3/d7/7f4354e69f10a917e5c7d5d72a499ef2e10945312f5e72c414a0a08d2ae4/pyclipper-1.4.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "6c317e182590c88ec0194149995e3d71a979cfef3b246383f4e035f9d4a11826"

[[packages]]
name = "python-bidi"
version = "0.6.7"

[[packages.wheels]]
name = "python_bidi-0.6.7-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/c3/e8/1f86bf699b20220578351f9b7b635ed8b6e84dd51ad3cca08b89513ae971/python_bidi-0.6.7-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "8a17631e3e691eec4ae6a370f7b035cf0a5767f4457bd615d11728c23df72e43"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/23/20/bb6982b26a40bb43951265ba29d4c246ef0ff59c9fdcdf0ed04e0687de4d/pyyaml-6.0.3-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "4a2e8cebe2ff6ab7d1050ecd59c25d4c8bd7e6f400f5f82b96557ac0abafd0ac"

[[packages]]
name = "scikit-image"
version = "0.26.0"

[[packages.wheels]]
name = "scikit_image-0.26.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/8d/5b/0671dc91c0c79340c3fe202f0549c7d3681eb7640fe34ab68a5f090a7c7f/scikit_image-0.26.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "0660b83968c15293fd9135e8d860053ee19500d52bf55ca4fb09de595a1af650"

[[packages]]
name = "scipy"
version = "1.17.0"

[[packages.wheels]]
name = "scipy-1.17.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/9f/ec/42a6657f8d2d087e750e9a5dde0b481fd135657f09eaf1cf5688bb23c338/scipy-1.17.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "3625c631a7acd7cfd929e4e31d2582cf00f42fcf06011f59281271746d77e061"

[[packages]]
name = "setuptools"
version = "82.0.0"

[[packages.wheels]]
name = "setuptools-82.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e1/c6/76dc613121b793286a3f91621d7b75a2b493e0390ddca50f11993eadf192/setuptools-82.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "70b18734b607bd1da571d097d236cfcfacaf01de45717d59e6e04b96877532e0"

[[packages]]
name = "shapely"
version = "2.1.2"

[[packages.wheels]]
name = "shapely-2.1.2-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/74/d4/135684f342e909330e50d31d441ace06bf83c7dc0777e11043f99167b123/shapely-2.1.2-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "a444e7afccdb0999e203b976adb37ea633725333e5b119ad40b1ca291ecf311c"

[[packages]]
name = "sympy"
version = "1.14.0"

[[packages.wheels]]
name = "sympy-1.14.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e091cc3e99d2141a0ba2847328f5479b05d94a6635cb96148ccb3f34671bd8f5"

[[packages]]
name = "tifffile"
version = "2026.1.28"

[[packages.wheels]]
name = "tifffile-2026.1.28-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/09/19/529b28ca338c5a88315e71e672badc85eef89460c248c4164f6ce058f8c7/tifffile-2026.1.28-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "45b08a19cf603dd99952eff54a61519626a1912e4e2a4d355f05938fe4a6e9fd"

[[packages]]
name = "torch"
version = "2.10.0"

[[packages.wheels]]
name = "torch-2.10.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/56/97/078a007208f8056d88ae43198833469e61a0a355abc0b070edd2c085eb9a/torch-2.10.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "6528f13d2a8593a1a412ea07a99812495bec07e9224c28b2a25c0a30c7da025c"

[[packages]]
name = "torchvision"
version = "0.25.0"

[[packages.wheels]]
name = "torchvision-0.25.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/1f/eb/d0096eed5690d962853213f2ee00d91478dfcb586b62dbbb449fb8abc3a6/torchvision-0.25.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "d1abd5ed030c708f5dbf4812ad5f6fbe9384b63c40d6bd79f8df41a4a759a917"

[[packages]]
name = "typing-extensions"
version = "4.15.0"

[[packages.wheels]]
name = "typing_extensions-4.15.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f0fa19c6845758ab08074a0cfa8b7aecb71c999ca73d62883bc25cc018c4e548"
